# Generated by Django 2.2.6 on 2020-02-11 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Housedata',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('X1', models.FloatField()),
                ('X2', models.FloatField()),
                ('X3', models.FloatField()),
                ('X4', models.FloatField()),
                ('X5', models.FloatField()),
                ('X6', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Price_of_unit_area',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Y', models.FloatField()),
            ],
        ),
    ]
